#! /bin/sh

case "$1" in
    start)
        printf "Starting aesdsocket: "
        start-stop-daemon -S -n aesdsocket --exec /usr/bin/aesdsocket -- -d
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    stop)
        echo "Stopping aesdsocket"
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0